[package]
name = "chipanel"
version = "0.1.0"
edition = "2021"
authors = ["ChiPanel Maintainers"]
description = "ChiPanel - Lightweight Homelab & Podman Management Console"

[dependencies]
axum = { version = "0.7", features = ["ws", "macros", "multipart"] }
tokio = { version = "1.38", features = ["rt", "rt-multi-thread", "net", "macros", "time", "signal", "io-util", "fs"] }
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }
tokio-tungstenite = "0.21"
jsonwebtoken = "9.3"
argon2 = "0.5"
hyper = { version = "1.4", features = ["server", "client", "http1"] }
hyper-util = { version = "0.1", features = ["tokio", "server", "client", "http1"] }
http-body-util = "0.1"
tokio-util = { version = "0.7", features = ["io"] }
fastnbt = "2.5"
flate2 = "1.0"
reqwest = { version = "0.12", features = ["json", "stream"] }
libc = "0.2"
thiserror = "1.0"
anyhow = "1.0"
hex = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
futures-util = "0.3"
zip = "2.1"
zbus = { version = "5", default-features = false, features = ["tokio"] }
sha1 = "0.10"
sha2 = "0.10"
percent-encoding = "2.3"
similar = "2.4"


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

